# Phép toán với Tensor

## Element Wise

In [1]:
import numpy as np

In [2]:
x = np.array([[-2,3],[-4,5]])
y = np.array([[1,2],[3,4]])

In [3]:
# element-wise :
print("x + y = \n",x+y)
# element-wise relu :
z = x+y
z = np.maximum(z, 0)

print("shape of z : ",z.shape)
print(z)

x + y = 
 [[-1  5]
 [-1  9]]
shape of z :  (2, 2)
[[0 5]
 [0 9]]


## Broadcasting 
Khi ta thực hiện phép cộng 2D tensor với 1 vector? what'll happend ?

In [4]:
# cong vector mxn voi vector n*1
a = np.array([[1,2,3],[4,5,6]])
b = np.array([2,6,12])

In [5]:
print(a.shape)
print(len(b.shape))

(2, 3)
1


In [6]:
print("a = \n",a)
print("b = \n",b)
print("a+b = \n",a+b)

a = 
 [[1 2 3]
 [4 5 6]]
b = 
 [ 2  6 12]
a+b = 
 [[ 3  8 15]
 [ 6 11 18]]


### Hình dung broadcasting với 2D tensor và vector :
vector b (1x3) sẽ được lặp lại n = 2 lần rồi thực hiện element-wise 
với tensor a (2 x 3)

### Broadcasting sẽ thực hiện khi : 
tensor lớn : có shape (a,b,...n,n+1,...m) </br>
tensor nhỏ : có shape (n,n+1,...m) </br>

## Phép nhân ma trận ( dot )
Trong numpy, element-wise nhân dùng dấu * </br>
Còn nhân ma trận, ta dùng .dot

In [7]:
a = np.array([[1,2,3],[4,5,6]])
b = np.array([[1],[4],[9]])
a.dot(b)

array([[36],
       [78]])

In [8]:
def matrix_dot(x,y):
    assert len(x.shape) == 2
    assert len(y.shape) == 2
    assert x.shape[1] == y.shape[0] # dam bao mxn dot nxl
    z = np.zeros([x.shape[0],y.shape[1]])
    for i in range(x.shape[0]):
        for j in range(y.shape[1]):
            z[i,j] = x[i,:].dot(y[:,j]) #worked
            # z[i,j] = np.sum(x[i,:] * y[:,j].T) #worked
            
    z = z.astype(int)
    return z

In [9]:
matrix_dot(a,b)

array([[36],
       [78]])

### Nhân tensor với dim > 2 
Tuân theo quy tắc : </br>
(a, b, c, d) . (d, ) -> (a,b,c) </br>
(a, b, c, d) . (d,e) -> (a,b,c,e)

## Reshape


In [10]:
# Cac gia tri khong thay doi, chi thay doi shape 
x = np.array([[0,1],
             [2,3],
             [4,5]])

In [11]:
a = np.reshape(x,6) # hoac a = x.reshape((6,1))
print(a)

[0 1 2 3 4 5]


In [12]:
b = np.reshape(x,[2,3]) # hoac b = x.reshape((2,3))
print(b)

[[0 1 2]
 [3 4 5]]


### Transpose 

In [13]:
x = x.T # hoac x = np.transpose(x)
print(x)

[[0 2 4]
 [1 3 5]]
